#!/usr/bin/env bash

set -e

NAME="podlab"
VERSION="1.2.1"
LABEL="org.$NAME"
IMAGE_NAME="$NAME"
NETWORK="$NAME"
DISTRONAME="podLAB pod image"
# Other tested images: "fedora:38"
BASE_IMAGE="quay.io/centos/centos:stream9"

SSH_KEY_NAME="ansible_ed25519"
SSH_KEY_TYPE="ed25519"
SSH_PATH=".ssh"

STUDENT_USERNAME='student'
STUDENT_PASSWORD='student'
