#!/usr/bin/env bash

set -e

PACKAGES="basesystem lsof whois mkpasswd ncurses bash systemd openssh-server passwd sudo python3 yum dnf findutils iproute NetworkManager iputils bind-utils procps-ng openssh-clients nc at hostname acl xz zip info wget bzip2 file ed nano quota less which strace symlinks tcpdump time tree jq vim-enhanced words util-linux-user rhel-system-roles firewalld"

ENVFILE="$(dirname $(realpath $0))/setenv"
if [[ -f $ENVFILE ]]; then
    . $ENVFILE
fi

if ! [ -x "$(command -v buildah)" ]; then
    echo "buildah is not installed" >&2
    exit 1
fi

if ! [ -x "$(command -v ssh-keygen)" ]; then
    echo "ssh-keygen is not installed" >&2
    exit 1
fi

if [[ ! -d $(realpath $SSH_PATH) ]]; then
    mkdir -p $(realpath $SSH_PATH)
fi

KEY_PATH="$(realpath $SSH_PATH)/$SSH_KEY_NAME"

if [[ ! -f $KEY_PATH ]]; then
    ssh-keygen -t $SSH_KEY_TYPE -f $KEY_PATH -C "ansible-lab key" -N ""
    FORCE_REGENERATE=1 # If key has been created, we need to regenerate the container image
fi

if [[ -z $(podman network ls -f "name=$NETWORK" --format {{.ID}}) ]]; then
    NET=`podman network create --label "$LABEL.version=$VERSION" $NETWORK`
fi

unset BUILDER

if [[ -n $(buildah ps --filter=name=$NAME-working-container --format {{.ContainerID}}) ]]; then
    # Recover a building image
    if [[ $(buildah inspect --format "{{index .OCIv1.Config.Labels \"$LABEL.version\"}}" $NAME-working-container) != $VERSION ]]; then
        echo Builder version mismatch, please run \'buildah rm $NAME-working-container\'. >&2
        exit 2
    fi
    BUILDER="$NAME-working-container"
    elif [[ -z $(podman image list --filter label=$LABEL.version=$VERSION --filter "label=$LABEL.packages=$PACKAGES" --format {{.ID}}) ]]; then
    BUILDER=$(buildah from --name "$NAME-working-container" "$BASE_IMAGE")
fi


if [[ -n $BUILDER ]]; then
    buildah config --label "$LABEL.version=$VERSION" \
    --label "$LABEL.packages=$PACKAGES" \
    --label "$LABEL.base=$BASE_IMAGE" \
    --label "org.label-schema.name=$DISTRONAME" \
    --label "org.label-schema.vendor=$NAME" \
    $BUILDER
    buildah run $BUILDER -- dnf -y install $PACKAGES
    buildah run $BUILDER -- sh -c "id -u ansible &>/dev/null || useradd ansible -rmG wheel"
    buildah add --chown ansible:ansible --chmod 600 $BUILDER $KEY_PATH.pub /home/ansible/.ssh/authorized_keys
    buildah run $BUILDER -- sh -c 'mkdir -p /etc/sudoers.d/ && echo -e "ansible ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ansible'
    buildah run $BUILDER -- sh -c "useradd $STUDENT_USERNAME --groups wheel --password \`mkpasswd $STUDENT_PASSWORD\`"
    buildah run $BUILDER -- sh -c "echo -e PermitRootLogin yes >> /etc/ssh/sshd_config"
    buildah run $BUILDER -- sh -c "rm -rf /var/cache/dnf/"
    buildah commit $BUILDER $IMAGE_NAME:$VERSION
    buildah rm $BUILDER
fi
